name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: welcome
              run: echo "my first message"

            - name: first
              run: echo "well"
              
            - name: list files
              run: ls

            - name: readme
              run: cat README.md